Fix broken `make go-test` command
This was due to conflicts in the dependencies

  === Errors
  Error: ../../../go/pkg/mod/github.com/anaskhan96/soup@v1.2.5/soup.go:20:2: missing go.sum entry for module providing package golang.org/x/net/html (imported by github.com/anaskhan96/soup); to add:
  	go get github.com/anaskhan96/soup@v1.2.5
  Error: ../../../go/pkg/mod/github.com/anaskhan96/soup@v1.2.5/soup.go:21:2: missing go.sum entry for module providing package golang.org/x/net/html/charset (imported by github.com/anaskhan96/soup); to add:
  	go get github.com/anaskhan96/soup@v1.2.5

Running `go mod tidy` fixes the issue and this commit contains the
updated go.mod and go.sum files.